### ISSUE TITLE
Offline UI: can't sign in while offline

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-mobile-client#2375]
If the user views the sign in screen and didn't previously sign in while online, they will be unable to sign in. Display an alert to inform them of this.

References: 
- https://github.com/techmatters/terraso-product/issues/1117

## Design
[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=9314-5289&node-type=frame&t=aNOkjDj8zfXau8az-0)
<img width="268" alt="image" src="https://github.com/user-attachments/assets/fae34b59-7784-47de-88c3-04a89f20c36e">

## Acceptance Criteria
- [ ] If offline without a valid session
   - [ ] Disable sign in buttons
   - [ ] display alert

**Comment by paulschreiber** [comment]
Please verify in 217 or later.

**Comment by DerekCaelin** [comment]
Looks good to me!

**Comment by CourtneyLee333** [comment]
@paulschreiber @DerekCaelin  the body text doesn't use the color defined in the design. I'm also not sure if the icon is the right size. I wouldn't say this blocks pushing the work, but if we close this ticket we should make a tech debt one for those things.

**Comment by paulschreiber** [comment]
@CourtneyLee333 Text color is fixed in 218. Let me know about the icon size.

**Comment by CourtneyLee333** [comment]
@paulschreiber The text color of the sentence still doesn't appear to be correct in 218. And I can't detect any difference in the icon size. To be clear, I don't have a way to know what size it is, I just wanted to make sure it was the right size.

**Comment by CourtneyLee333** [comment]
Closing this, with the expectation that the details will get fixed in the component implementation issue.
